apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: {{ .Values.deployment.namespace }}
data:
  enabled_plugins: |
    [rabbitmq_tracing, rabbitmq_shovel, rabbitmq_shovel_management, rabbitmq_delayed_message_exchange, rabbitmq_consistent_hash_exchange, rabbitmq_management, rabbitmq_peer_discovery_k8s].

  rabbitmq.conf: |
    # =====================================================================================
    # Cluster formation. See https://www.rabbitmq.com/cluster-formation.html to learn more.
    # =====================================================================================

    ### -----------------------------------------------------------------------------------
    ### Specifying the Peer Discovery Mechanism
    ### https://www.rabbitmq.com/cluster-formation.html#peer-discovery-configuring-mechanism
    cluster_formation.peer_discovery_backend = {{ .Values.deployment.cluster_formation_peer_discovery_backend }}

    ### -----------------------------------------------------------------------------------
    ### Kubernetes for peer discovery:
    cluster_formation.k8s.host = {{ .Values.deployment.cluster_formation_k8s_host }}

    ### -----------------------------------------------------------------------------------
    ### should result set use hostnames or IP addresses
    ### of Kubernetes API-reported containers?
    ### supported values are "hostname" and "ip"
    cluster_formation.k8s.address_type = {{ .Values.deployment.cluster_formation_k8s_address_type }}

    ### -----------------------------------------------------------------------------------
    # Should RabbitMQ node name be computed from the pod's hostname or IP address?
    # IP addresses are not stable, so using [stable] hostnames is recommended when possible.
    # Set to "hostname" to use pod hostnames.
    # When this value is changed, so should the variable used to set the RABBITMQ_NODENAME
    # environment variable.
    cluster_formation.k8s.service_name = rabbitmq-headless

    # load_definitions = /etc/rabbitmq/new_definitions.conf
